### PR TITLE
KMP support

### LINKED ISSUE #10: KMP support
This library can be easily converted to a multiplatform one since it uses `kotlinx-coroutines` (with 100% multiplatform support) and KSP that can generate common code. So, it will be possible to use the same code for multiple platforms such as:

- Android
- JVM (ex: Jetbrains Compose applications)
- JS (ex: React or Jetbrains Compose applications)
- iOS (shared view model with Android)

### PR DESCRIPTION
**Pull request by DVDAndroid**
Fixes #10 

Adds KMP support including Android, JVM, JS (both browser and NodeJS), iOS (needs a macOS host to build&publish)

I've added the `application` plugin to the `example` project to check if nothing broken. You can run `./gradlew run`

### CODE REVIEW

**Comment by DVDAndroid** [comment]
iOS multiplatform needs testing, since I don't use a macOS host

Updated `README.md`

**Comment by PatilShreyas** [comment]
Thanks, @DVDAndroid for contributing and making this KMP compatible!

**Comment by PatilShreyas** [comment]
Hi @DVDAndroid, since I'm new to this KMP thing, need to discuss it with you.

So I have questions:
1. Existing publish workflow will work or needs to be changed?
2. Is it necessary to add the android framework to the picture? Can't we just publish it as a pure JVM dependency? Because we are not having any android specific dependency as such. So I believe android projects can consume JVM dependency without any issues.

**Comment by DVDAndroid** [comment]
> 1. Existing publish workflow will work or needs to be changed?

No changes needed. I've run `./gradlew publishToMavenLocal` (with signature disabled for testing) and I got the libraries "published" to my Maven local directory. I don't think it's different when publishing to MavenCentral

> 2. Is it necessary to add the android framework to the picture? Can't we just publish it as a pure JVM dependency? Because we are not having any android specific dependency as such. So I believe android projects can consume JVM dependency without any issues.

Yeah it may be right. There's a [Kotlin issue (KT-52666)](https://youtrack.jetbrains.com/issue/KT-52666) discussing this.

However, I like to always declare which platforms my library is going to support and to avoid any possible incompatibility. Since I'm not even sure this is the right answer, I'll ask on Kotlin Slack. I'll update here.

---
If you are not sure about KMP support, I can always maintain my fork without problems

**Review by PatilShreyas — APPROVED** [review]

**Comment by PatilShreyas** [comment]
@DVDAndroid Thanks for the contribution, looks good to me 👍🏻. I am merging this into a separate branch to have experiments and tests.

**Pull request merged**
